change textarea for div to show the mnemonic seed
polkadot-js/extension pull request #1147
Opened 2022-09-26 10:58 UTC by Gioyik

_context:_
the browser stores input/textarea values in tabs into plain text files in disk to restore content in case of a browser crash, unexpected closing or session restore. Multiple wallets and signers used textarea to show the generated Mnemonic Phrase seeds, obtaining the risk of getting into a situation like [this](https://halborn.com/halborn-discovers-critical-vulnerability-affecting-crypto-wallet-browser-extensions/).

_proposal:_
show the Mnemonic Phrase seed in a non input type HTML Element to avoid leaking of phrase in the cases mentioned before. With this change, it looks the same and for the user should not represent any change, there is a TODO related to the approach to the clipboard, as I still haven't check if using the Clipboard API requires asking for the additional permission to the browser.

2022-09-26 11:16 UTC, jacogr commented
The approach sounds sane - will take a look.

2022-10-18 10:20 UTC, jacogr commented
Failing both linting & tests. (Running `yarn lint` locally should address)

2023-01-22 16:21 UTC, Tbaut commented
@Gioyik Any chance you can fix the nit please so that we can merge?

2023-01-23 12:05 UTC, Tbaut commented
I don't have a strong opinion on it, so I went ahead and checked what has been used in other implementations such as the `@polkadot/react-identicon` package. We use an external package there called `react-copy-to-clipboard`, [here](https://github.com/polkadot-js/ui/blob/master/packages/react-identicon/src/Identicon.tsx#L8) which is itself using [`copy-to-clipboard`](https://www.npmjs.com/package/copy-to-clipboard). So I'd go for this :shrug:

2023-02-10 17:21 UTC, Tbaut requested changes
Thank you. It looks good beside one thing that was added and that I disagree with. I think users should read and manually check the box, since copying doesn't mean that it is saved safely.

2023-02-10 17:21 UTC, Tbaut commented on packages/extension-ui/src/Popup/CreateAccount/Mnemonic.tsx
> +    setIsMnemonicSaved(true);
copying doesn't mean that the users have saved the mnemonic safely. I'd suggest to keep the manual checkbox as it was.

```suggestion
```

2023-02-11 23:32 UTC, Tbaut approved these changes
Thanks, looks good. I tested on Brave

2023-03-20 07:55 UTC, jacogr requested changes
All good. Happy to merge as-is.

(Could you just merge in master one last time to resolve conflicts, once done will approve)

2023-03-20 23:18 UTC, Tbaut commented
Could you check again @Gioyik, the lint and build failed.

2023-03-21 11:39 UTC, Gioyik commented
@Tbaut @jacogr fixed. Sorry, I forgot to check it builds before pushing. Should be good now.

2023-03-21 11:55 UTC, Tbaut commented on packages/extension-ui/src/Popup/CreateAccount/Mnemonic.tsx
> +    setIsMnemonicSaved(true);
This is still here BTW. Please remove it.

2023-03-21 11:57 UTC, Tbaut commented
The `setIsMnemonicSaved(true);` slipped in again unfortunately. Please remove it.

2023-03-21 12:05 UTC, Gioyik commented
@Tbaut done

2023-03-21 15:12 UTC, jacogr approved these changes
Thank you.

2023-03-21 15:12 UTC, merged