Upgrade `web3` dependency in `extension-compat-metamask`
polkadot-js/extension pull request #1340
Opened 2024-03-27 08:10 UTC by gdethier

We are relying on `extension-compat-metamask` in our project to interact with MetaMask. However, the old `web3` dependency triggers dependabot alerts that can't be solved without upgrading.

We built a [custom package](https://www.npmjs.com/package/@logion/extension-compat-metamask) from the code in this PR (happy to remove it as soon as a new release contains this change) for testing the upgrade and everything seems to work as expected.

2024-04-18 13:53 UTC, TarikGul requested changes
Thanks for the patience. Conflicts just need to be resolved.

2024-04-23 08:48 UTC, gdethier commented
@TarikGul could you approve the merge? Otherwise, there will be conflicts again...

2024-04-23 12:45 UTC, TarikGul commented
@gdethier Yes I will merge this today, and dont worry no other PR will go in before this. I just need to double check the changes between the web3 versions.

2024-04-23 13:03 UTC, gdethier commented
Great, thanks!

2024-04-23 13:13 UTC, TarikGul approved these changes
So AFAIK the web3 package is only used for the `utils.sha3` signature, which has only seen some benefits in the CHANGELOG notes from what I can tell. LGTM

2024-04-23 13:14 UTC, merged