feat: Add support for the Ledger Generic App [WIP]
polkadot-js/extension pull request #1408
Opened 2024-07-23 15:00 UTC by bee344

DO NOT MERGE

This replaces #1397 .

Needs to be ran alongside [#10778](https://github.com/polkadot-js/apps/pull/10777), because that has the support to uploading the metadata to the extension.

2024-07-24 17:09 UTC, TarikGul commented on packages/extension-ui/src/Popup/Signing/LedgerSign.tsx
> +  const m = chain.definition.rawMetadata || '0x00';
I think we should rework this little portion, when no metadata is present there should be some sort of error that is thrown, and logged on the screen.

2024-07-24 17:10 UTC, TarikGul commented on packages/extension-ui/src/hooks/useLedger.ts
> +    ledger.getAddress(chainInfo?.ss58Format || 0, false, accountIndex, addressOffset)
Maybe we can do an `assert` here - We just want to make sure the ss58 is always for certain what is present in the ss58 format and can't resolve to `0`

2024-07-24 21:02 UTC, TarikGul requested changes
There are 2 little nits I have - But I also think we should have some way to warn about no metadata being present when users are using their ledger account

2024-07-24 21:03 UTC, TarikGul commented
Also we should consider what the workflow is also going to look like for the migration app.

2024-07-25 18:56 UTC, TarikGul approved these changes
LGTM, great job - this will be followed up with support for the Migration App.

2024-07-26 22:10 UTC, bee344 commented
@TarikGul Currently you have to add a new account for every chain, even though the derivation paths are the same, so it's kind of annoying. We could eventually add a "Allow use on any network" option like when creating via mnemonic.

2024-07-29 12:03 UTC, merged